# Generated by Django 5.0.6 on 2024-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='Catatan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='HpOrtu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='NIS',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='Nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='NamaOrtu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
