# Generated by Django 5.0.6 on 2024-05-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_alter_kelas_tingkat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kelas',
            table='kelas',
        ),
    ]
