# Generated by Django 5.0.6 on 2024-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_alter_kelas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='Nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='Tingkat',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
