# Generated by Django 5.0.6 on 2024-05-16 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0002_alter_sekolah_notelp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Poin', models.CharField(max_length=20)),
                ('Pesan', models.CharField(max_length=100)),
                ('Catatan', models.CharField(max_length=200)),
                ('SekolahId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'db_table': 'pelanggarann_kategori',
            },
        ),
    ]
