# Generated by Django 5.0.6 on 2024-05-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_alter_sekolah_notelp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sekolah',
            table='sekolah',
        ),
    ]
