# Generated by Django 5.0.6 on 2024-05-16 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelanggarann_kategori', '0001_initial'),
        ('petugas', '0001_initial'),
        ('sekolah', '0002_alter_sekolah_notelp'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggarann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TglJam', models.DateTimeField(auto_now_add=True)),
                ('Poin', models.CharField(max_length=20)),
                ('Catatan', models.CharField(max_length=200)),
                ('KategoriId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggarann_kategori.kategori')),
                ('PetugasId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.petugas')),
                ('SekolahId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('SiswaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'db_table': 'pelanggarann',
            },
        ),
    ]
