# Generated by Django 5.0.6 on 2024-05-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggarann', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggarann',
            name='Catatan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggarann',
            name='Poin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pelanggarann',
            name='TglJam',
            field=models.DateTimeField(),
        ),
    ]
